sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_853bcbd6090d_key -iv $encrypted_853bcbd6090d_iv -in multi-k8s-fd4c2123349d.json.enc -out multi-k8s-fd4c2123349d.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-fd4c2123349d.json
  - gcloud config set project multi-k8s-243622
  - gcloud congig set compute/zone us-west1-a
  - gcloud container clusters get-credentials multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t wanwanzainer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wanwanzainer/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
