apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-pod
    kind: ClusterIssuer
  commonName: simonho.app
  dnsName:
    - simonho.app
    - www.simonho.app
  acme:
    config:
      - http01:
          ingressClasses: nginx
        domains:
          - simonho.app
          - www.simonho.app
